# Generated by Django 5.0.7 on 2024-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_number',
            field=models.SmallIntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
