# Generated by Django 5.0.7 on 2024-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_sprite_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_number',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
