# Generated by Django 5.0.7 on 2024-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_pokemon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
