# Generated by Django 5.0.7 on 2024-08-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemon_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_number',
            new_name='national_pokedex_number',
        ),
        migrations.AlterField(
            model_name='stat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokedex.pokemon'),
        ),
    ]
